fix: recover lost function arguments and argument types
googleapis/sphinx-docfx-yaml pull request #93
Opened 2021-08-12 22:42 UTC by dandhlee

Before you open a pull request, note that this repository is forked from [here](https://github.com/docascode/sphinx-docfx-yaml/).
Unless the issue you're trying to solve is unique to this specific repository, 
please file an issue and/or send changes upstream to the original as well.

__________________________________________________________________

When there is a `*` argument present in the function signature, they are not included in `args` from `inspect.getfullargspec` function. Iterating through the entire list to make sure everything has been counted for will ensure all variables are accounted for.

As well, when there isn't a docstring entry for functions they only had their names (`id`) included in the table of parameters. Recovering their types if specified in the function signature, otherwise they'll be removed to have the tables not look so empty.

Fixes internally filed issue.

> It's a good idea to open an issue first for discussion.

- [x] Tests pass
- [ ] Appropriate changes to README are included in PR

2021-08-12 23:24 UTC, dandhlee commented
Ran a test Kokoro job, seems to work fine but it failed on `python-bigquery-sqlalchemy` which is expected - it currently produces no documentation for DocFX YAML.

2021-08-13 13:37 UTC, tbpg requested changes
Any tests? :smile:

2021-08-13 13:37 UTC, tbpg commented on docfx_yaml/extension.py
> +                            args[len(args) - cut_count + count]['defaultValue'] = str(default)
I don't understand `len(args) - cut_count + count`. Can you clarify in a comment, different variable names, or something else?

2021-08-13 13:37 UTC, tbpg commented on docfx_yaml/extension.py
> +        # Add any variables we might have missed from extraction.
Do we need to worry about order of arguments?

2021-08-13 13:37 UTC, tbpg commented on docfx_yaml/extension.py
> +        for variable in variables:
Could we have a single loop over `variables` and not `args`?

2021-08-13 16:14 UTC, dandhlee reviewed
Hard to make a specific unit test for the added bits as they need to be part of Sphinx with `app`, it would be easier to have this with the goldens, planning to fix it in #44.

2021-08-13 16:16 UTC, tbpg approved these changes

2021-08-13 16:34 UTC, merged